### PR TITLE
Utilize lxdhelper library for certain functions

### PR DESCRIPTION
**Pull request by jtopjian**

### CODE REVIEW

**Comment by jtopjian** [comment]
@sl1pm4t Looks like the `LXD_PASSWORD` environment variable isn't being set?

**Comment by sl1pm4t** [comment]
@jtopjian  Strange about LXD_PASSWORD... that part worked OK in my last build (an hour ago)

**Comment by jtopjian** [comment]
Here are the Travis settings from my point of view. I wonder if it's a permissions issue:

screen shot 2017-06-06 at 1 30 39 pm

**Comment by sl1pm4t** [comment]
Must be this travis change:
https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

I guess there's no reason to hide the password, seeing as the env is ephemeral.

**Pull request merged**
