### PR TITLE
Fix hashing of file contents in Terraform state

### PR DESCRIPTION
**Pull request by jtopjian**
This should work around the issue discovered in #63

### CODE REVIEW

**Comment by jtopjian** [comment]
cc @shantanugadgil

**Comment by jtopjian** [comment]
I'm still going to investigate an `lxd_file` resource. This is just to workaround the bug of #63

**Comment by shantanugadgil** [comment]
@jtopjian I'll give this a try and let you know.
+1 for `lxd_file` if you do decide on it.

**Comment by shantanugadgil** [comment]
@jtopjian  I am no longer sure why the same symptom keeps occurring on my setup.

I used the new branch as can be seen here `jtopjian:container-file-hash-fix`

I think I'll try to complete other things before I get back to experimenting with large files in the `file` block.

**Comment by jtopjian** [comment]
@shantanugadgil which symptoms? Is the Terraform state file still large?

**Comment by shantanugadgil** [comment]
Yes, `terraform.tfstate` file grows large (~52 MB).
I think it is filled with the "\x000" byte values of the file itself.
And quite often the `apply` fails with a "connection lost" message.

**Comment by jtopjian** [comment]
Yeah, that's definitely strange. With this patch applied, I see the following in my state file:

```json
"lxd_container.test1": {
    "type": "lxd_container",
    "depends_on": [],
    "primary": {
        "id": "test1",
        "attributes": {
            "config.%": "1",
            "config.limits.memory": "2GB",
            "ephemeral": "false",
            "file.#": "1",
            "file.0.content": "8c206a1a87599f532ce68675536f0b1546900d7a",
            "file.0.create_directories": "false",
            "file.0.gid": "0",
            "file.0.mode": "0644",
            "file.0.target_file": "/tmp/foo.txt",
            "file.0.uid": "0",
            "id": "test1",
            "image": "ubuntu",
            "ip_address": "10.3.184.70",
            "mac_address": "00:16:3e:86:cc:95",
            "name": "test1",
            "privileged": "false",
            "profiles.#": "1",
            "profiles.0": "default",
            "status": "Running"
        },
        "meta": {},
        "tainted": false
    },
    "deposed": [],
    "provider": ""
}```

**Comment by shantanugadgil** [comment]
FWIW, this my example lxd_container definiton

```hcl
resource "lxd_container" "s3" {
  remote    = "..."
  name      = "..."
  image     = "..."
  ephemeral = false
  profiles  = ["${var.profiles}"]

    file {
      content     = "${file("config/minio.bin")}"
      target_file = "/tmp/minio"
      uid         = 0
      gid         = 0
      mode        = "0755"
    }
}
```

The minio binary is from here:
https://dl.minio.io/server/minio/release/linux-amd64/minio

**Comment by sl1pm4t** [comment]
FYI @jtopjian  - as another workaround for this, I experimented with enabling the `Sensitive` flag on the `file` `contents` attribute.
With that change, the Terraform no longer burns CPU cycles and dumps the contents of the file to output, it does however still store the full contents of the file in the .tfstate file, so still not ideal.

**Comment by shantanugadgil** [comment]
cross-referencing #53 for high CPU usage

**Comment by jtopjian** [comment]
@sl1pm4t Are you still seeing high CPU usage with this change? And just to confirm: the hash is being stored in the state file for you?

Does adding `Sensitive` resolve the CPU issue for you?

**Comment by sl1pm4t** [comment]
@jtopjian - I think was only seeing high CPU when the file contents were being dumped to output, and so the `sensitive` flag fixed that - however I'll double check when I get a chance later today.

**Comment by shantanugadgil** [comment]
@sl1pm4t Did you get a chance to experiment again?

Thanks,
Shantanu

**Comment by sl1pm4t** [comment]
Sorry everyone - life got busy for a while.
Looking at this now.

**Comment by sl1pm4t** [comment]
With the sensitive fix I don't see high CPU during `apply` or `plan` phases.

**Comment by sl1pm4t** [comment]
Actually - I also tested without the `sensitive` flag, but built against `Terraform v0.10.0-dev (f40df21988572d5dfa4830bb5685a0c3134271ba)` build and also didn't reproduce high CPU. 

So maybe it's not needed now, because the issue @jtopjian identified is fixed in Terraform.

**Comment by jtopjian** [comment]
> Sorry everyone - life got busy for a while.

No worries at all :smile:

**Pull request merged**
