### PR TITLE
#135: User opt-in to wait for network

### PR DESCRIPTION
**Pull request by renonat**
Feature request #135
Add `wait_for_network` argument to lxd_container resource. This argument allows `resourceLxdContainerWaitForNetwork` to be opt-in instead of always-on.

### CODE REVIEW

**Comment by sl1pm4t** [comment]
My apologies @renonat  - I just saw @jtopjian's comment in #135 where he suggests the default value be `false`, so you had it correct first time around.

**Comment by jtopjian** [comment]
I'm OK either way. 

After doing further testing, the chances of running a container with no network connectivity is less likely to happen than the latter. Coupled with retaining backwards compatibility, a default value of `true` makes sense.

**Comment by jtopjian** [comment]
@renonat btw: thank you for implementing this. I've been meaning to get to this, but my cat-and-mouse game of hunting races/locks has kept me from it. :)

**Comment by renonat** [comment]
@jtopjian Not a problem, after all I felt some responsibility for putting the original change in a few months ago

**Pull request merged**
