### PR TITLE
Hash the contents of files

### PR DESCRIPTION
**Pull request by jtopjian**
This commit hashes the contents of a file before it stores it
in state. This is useful for large files.

For #53

### CODE REVIEW

**Comment by jtopjian** [comment]
@shantanugadgil This should solve #53 for you. Let me know if you're able to test it and if it resolves the problem you're seeing.

**Comment by shantanugadgil** [comment]
Terraform: Terraform v0.9.8

I tried but doesn't work, it still prints out the long string (17 MB long) and the same happens; high CPU during plan.
I went ahead and did apply anyway; it failed with: (s3 is the name of my minio `lxd_container`)
```
* lxd_container.s3: 1 error(s) occurred:

* lxd_container.s3: reading body session shutdown
```

This is how I checked out and built the branch:
```
git clone https://github.com/jtopjian/terraform-provider-lxd.git
cd terraform-provider-lxd/
git checkout container-file-hash
make
make build dev
# ls terraform-provider-lxd
terraform-provider-lxd
```

**Comment by sl1pm4t** [comment]
HI @shantanugadgil - did you copy the newly built binary into your `$PATH`? 
Perhaps try `cd $GOPATH/src/github.com/jtopjian/terraform-provider-lxd; go install -v`

I tried out this fix and it worked for me - before the fix a 12Mb file would hang terraform during a plan and afterwards the plan completed in a short time. 

Also, after `terraform apply` the file integrity was verified with an `md5sum` of the file inside vs outside the container.

**Comment by shantanugadgil** [comment]
@sl1pm4t  my build machine and tf submit hosts are different.
So I scp the `terraform-provider-lxd` and place it in the same directory as by `terraform` binary.

**Comment by sl1pm4t** [comment]
Yes, this seems to only be a partial fix. I was able to reproduce further issues here.
Terraform still hangs when running `plan` on an existing resource where a large file was pushed.

**Comment by shantanugadgil** [comment]
Yes, another side effect of this problem is that the file `terraform.tfstate` has gone to ~52MB.
Initially it would be < 1MB

**Comment by jtopjian** [comment]
This is looking like a bug in Terraform core. The changed value is being displayed during run, but not stored in the state. This seems to be only happening for nested elements of a List/Set.

This is applying correctly whenever applied to a top-level schema item. For example,

```go
"name": &schema.Schema{
  Type:     schema.TypeString,
  ForceNew: true,
  Required: true,
  StateFunc: func(v interface{}) string {
    return v.(string) + "!!!"
  },
},
```

I'll inquire about this on Monday, but if it is a core bug there are two things we can do:

1. Leave this as-is
2. Modify the `file.content` argument to do a validation check. Anything over a certain size will trigger an error and not proceed.

**Comment by jtopjian** [comment]
Another possibility is to create a first-class `lxd_file` resource.

**Pull request merged**
