### PR TITLE
Docs Refactor

### PR DESCRIPTION
**Pull request by jtopjian**
For #111 

You can view the rendered documentation here: https://github.com/jtopjian/terraform-provider-lxd/tree/docs

This follows conventions of the core Terraform providers documentation format.

### CODE REVIEW

**Comment by shantanugadgil** [comment]
the version number could be updated to the 1.0.0 ?!?
https://github.com/sl1pm4t/terraform-provider-lxd/releases/download/v1.0.0/terraform-provider-lxd_v1.0.0_linux_amd64.tar.gz

**Comment by jtopjian** [comment]
@mjrider Thanks for the review. Since it's such a large change, I'll also wait until @sl1pm4t signs off on it.

@shantanugadgil I'm not sure what you mean?

**Comment by jtopjian** [comment]
Rebased

**Comment by shantanugadgil** [comment]
Sorry about the confusion. I meant that in the "example" download, the docs could refer to the 1.0.0 release rather than the 0.10.2.

**Comment by jtopjian** [comment]
@shantanugadgil ahh - got it. I'll wait until after this is merged to make that change. It's always possible a new release will be made between now and if/when this is merged.

**Comment by jtopjian** [comment]
@sl1pm4t any thoughts on this?

**Comment by sl1pm4t** [comment]
Looks Great 👍🏼

**Pull request merged**
