### PR TITLE
Fix absence of linux.* attribute in config

### LINKED ISSUE #193: LXD provider does not work with "linux.kernel_modules" config property
When I use `linux.kernel_modules` in the `config` section of the `lxd_container`, provider passes it to LXD and properly creates the container, but after checking that the plan is equal to the applied state the property is absent in the state and as a result it produces changes.
As for "linux.kernel_modules" property it tries to re-create the container which is not valid behavior in this circumstances.

### PR DESCRIPTION
**Pull request by arren-ru**
Added support for linux.kernel_modules attribute in config section.

Fixes #193

### CODE REVIEW

**Comment by arren-ru** [comment]
Also I found a bunch of attributes which are not being merged into config schema.
https://lxd.readthedocs.io/en/latest/instances/#keyvalue-configuration
I would add all the namespaces listed on that page.

**Comment by jtopjian** [comment]
@arren-ru Thanks for submitting this. Can you rebase this on top of master? That should fix the Travis issue.

**Comment by arren-ru** [comment]
> @arren-ru Thanks for submitting this. Can you rebase this on top of master? That should fix the Travis issue.

Seems to be I already did that :)

**Comment by jtopjian** [comment]
Ah, yes - my mistake.

**Pull request merged**
