### PR TITLE
Fix test and travis build

### PR DESCRIPTION
**Pull request by mjrider**
- switch to go 1.9, terraform requires this 
- fixed the provider_test
- yamllint'ed .travis.yml

### CODE REVIEW

**Comment by jtopjian** [comment]
@mjrider Thanks for this, but please see #87 :)

The `SaveConfig` piece looks like it's a better solution to what I have, though. I was wondering about that part and felt wrong modifying the test case to account for it.

**Comment by jtopjian** [comment]
The travis settings look like they're a better fit, too. @sl1pm4t has them configured within Travis, but having them in the `.travis.yml` file makes them more accessible.

I'm in favor of closing #87 for this - I'll let @sl1pm4t decide that one, though.

**Comment by mjrider** [comment]
@jtopjian yeah, sorry, i was working on fixing the tests for a few days, and forget to check if somebody else also did same work in the meantime.

i tried to run the tests it complained that RemoteConfig and SaveConfig were not defined, and it lookt to me that the api of lxd changed. So i changed the test case to compensate for that.

Maybe it would be a good improvement to fix the vendored code with govendor, other terraform providers seem to use that.

**Comment by jtopjian** [comment]
> @jtopjian yeah, sorry, i was working on fixing the tests for a few days, and forget to check if somebody else also did same work in the meantime.

No problem at all. After review, I think this PR is much better. I would merge it, but just want @sl1pm4t to sign off on the travis changes.

> Maybe it would be a good improvement to fix the vendored code with govendor, other terraform providers seem to use that.

We've opted to not version so it forces us to keep up with LXD development since it changes so frequently. Versioning would set us back quite a ways.

**Comment by sl1pm4t** [comment]
Thanks @mjrider + @jtopjian

**Pull request merged**
