### PR TITLE
per #67

### PR DESCRIPTION
**Pull request by jfgibbins**
executes file push before starting container, so that files are available for startup routines

### CODE REVIEW

**Comment by sl1pm4t** [comment]
Hi @jfgibbins - thanks for your PR, although it looks like it had unintended side-effects and has broken the tests. Do you know if this use case (uploading files before container start) works outside of Terraform?

**Comment by jfgibbins** [comment]
Yes it does.  lxc push/pull works regardless of whether the container is working.  Also, fyi, I had already made the change locally, and it worked like a charm.  I use it to push files into /etc/network/if-up.d and to /etc/iproute2/rt_tables so that there available before the initial network start.  Please double check my edit, but it should just have been moving the file upload stanza from after container startup, to be between creation and startup.

**Comment by jfgibbins** [comment]
this is what the section looks like in the local copy that was compiled.  

        // Wait for the LXC container to be created
        err = client.WaitForSuccess(resp.Operation)
        if err != nil {
                return err
        }

        // Upload any files, if specified
        if v, ok := d.GetOk("file"); ok {
                for _, v := range v.([]interface{}) {
                        if err := resourceLxdContainerUploadFile(client, name, v); err != nil {
                                return err
                        }
                }
        }

        // Start container
        _, err = client.Action(name, shared.Start, -1, false, false)
        if err != nil {
                // Container has been created, but daemon rejected start request
                return err
        }

        // Wait until the container is in a Running state
        stateConf := &resource.StateChangeConf{
                Target:     []string{"Running"},
                Refresh:    resourceLxdContainerRefresh(client, name),
                Timeout:    3 * time.Minute,
                Delay:      refreshInterval,
                MinTimeout: 3 * time.Second,
        }

        if _, err = stateConf.WaitForState(); err != nil {
                return fmt.Errorf("Error waiting for container (%s) to become active: %s", name, err)
        }

        d.SetId(name)

        return resourceLxdContainerRead(d, meta)

**Comment by jtopjian** [comment]
Superseded by #76

**Comment by jtopjian** [comment]
@jfgibbins Thanks for submitting this. There were some changes to this block of code between when you originally submitted this and now, so I went ahead and merged an updated version. I also fixed the unit tests so everything passed in testing.

**Comment by jfgibbins** [comment]
Very cool.  Glad to know also why the tests failed.  So, sort of makes my first PR ever, lol.

**Pull request closed without merging**
